"""empty message

Revision ID: 312c5744aee8
Revises: 0e115dbe447e
Create Date: 2020-06-05 02:18:19.115118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312c5744aee8'
down_revision = '0e115dbe447e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
